Worked on Footer for mobile and desktop versions
alaminShaheen/irc-ui pull request #1
Opened 2024-03-09 18:41 UTC by farzanashampa7

2024-03-09 19:01 UTC, AsifOni commented
Please raise a PR against `develop` branch. Not main

2024-03-09 19:04 UTC, farzanashampa7 commented
I have changed the from main to develop

2024-03-09 19:09 UTC, AsifOni requested changes

2024-03-09 19:09 UTC, AsifOni commented on tailwind.config.js
> +        'sm': '414px',
I think we shouldn't define custom viewports here. Rather we will go with tailwind viewports. You can remove this.

2024-03-09 19:09 UTC, AsifOni commented on src/components/Footer/Footer.tsx
> +                    </a>
As per design, there are 3 social media links. So technically there should be 3 anchor tags each pointing to specific social media platform

2024-03-09 19:09 UTC, AsifOni commented on src/components/Footer/Footer.tsx
> +                    <a href="">
Anchor tag should have `target='_blank'`

2024-03-09 19:09 UTC, AsifOni commented on src/assets/socialMedia.svg
Social media svg should be seperated. Each one for single social platform

2024-03-09 19:09 UTC, AsifOni commented on src/components/Footer/Footer.tsx
> +import socialMedia from '../../assets/socialMedia.svg';
After library imports (like `react`) enter a new line and then import custom stuff. This will be a differentiator between library and custom imports

2024-03-09 19:09 UTC, AsifOni commented on src/components/Footer/Footer.tsx
> +const Footer: React.FC = () => {
We will not use `React.FC` method. It's a primitive way of defining typeScript which are not being followed by TypeScript community now a days. You can remove it

2024-03-09 19:16 UTC, AsifOni commented
**UI Issues**

Footer UI is not matching Figma. 

1. Line Should be above the privacy policy.F
2. Footer should be placed at the bottom of the page. But it's lifted up.
3. Text and line divider are not aligned.
4. Gap is more between paragraph and Company logo.
5. On mobile view, Privacy policy link and @2022 Copyright text are not aligned
6. In bigger screen, UI looks disconnected. From Laptop to bigger screen, design should match desktop view from Figma

**Desktop issue**

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/2ae44d75-28eb-4ada-a330-c3438d0ebf7f)

**Mobile issue**

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/6673c9ce-5401-4aa4-99d6-abb0e9c82454)

2024-03-11 01:26 UTC, AsifOni commented
Manually Merged code. Closing this PR

2024-03-11 01:26 UTC, closed without merging