Identity confirmation page
alaminShaheen/irc-ui pull request #23
Opened 2024-04-11 21:02 UTC by alaminShaheen

Is This You page UI implementation and tests completed

2024-04-11 21:44 UTC, CAADigitalOPS requested changes
**UI Issue**

1. Underline is missing in Sign up link

![image](https://github.com/alaminShaheen/irc-ui/assets/145376342/9d7fda73-bc3b-4a86-8c0b-f50e2e7ad227)

2. Instruction is not aligned with input controls as per Figma. Also first instruction is breaking into next line which differs from Figma.

![image](https://github.com/alaminShaheen/irc-ui/assets/145376342/6a672216-e44b-4367-8b4d-7458ba9ff0ea)

3. Disclaimer grid area not matching Figma

![image](https://github.com/alaminShaheen/irc-ui/assets/145376342/7d45656d-60de-4b4b-86f2-428c46948cb2)

AODA suggestion

I just realized none of the form fields are connected to error message which is necessary for AODA. See below image

![image](https://github.com/alaminShaheen/irc-ui/assets/145376342/700e5beb-fd71-428b-9a4c-43950d9d8ba2)

Check input box and bottom `span` holding error message. Requirement is if error appears then that should be bound with corresponding input element via `aria-describedby` attribute.

For an example

```
<div class="form-group has-error">
       <label for="firstName" class="form-label">First Name:</label>
       <input name="firstName" id="firstName" aria-describedby="first-name-error" class="input w-full py-5" type="text">
      <span class="error-warning" id="first-name-error">This field is required</span>
</div>
```
This `aria` attribute should only be attached to form element if error is present. Otherwise attribute should not be mentioned.

Let me know if you want to discuss further about it

2024-04-11 21:46 UTC, AsifOni requested changes
**UI Issue**

1. Underline is missing in Sign up link

![image](https://github.com/alaminShaheen/irc-ui/assets/145376342/9d7fda73-bc3b-4a86-8c0b-f50e2e7ad227)

2. Instruction is not aligned with input controls as per Figma. Also first instruction is breaking into next line which differs from Figma.

![image](https://github.com/alaminShaheen/irc-ui/assets/145376342/6a672216-e44b-4367-8b4d-7458ba9ff0ea)

3. Disclaimer grid area not matching Figma

![image](https://github.com/alaminShaheen/irc-ui/assets/145376342/7d45656d-60de-4b4b-86f2-428c46948cb2)

AODA suggestion

I just realized none of the form fields are connected to error message which is necessary for AODA. See below image

![image](https://github.com/alaminShaheen/irc-ui/assets/145376342/700e5beb-fd71-428b-9a4c-43950d9d8ba2)

Check input box and bottom `span` holding error message. Requirement is if error appears then that should be bound with corresponding input element via `aria-describedby` attribute.

For an example

```
<div class="form-group has-error">
       <label for="firstName" class="form-label">First Name:</label>
       <input name="firstName" id="firstName" aria-describedby="first-name-error" class="input w-full py-5" type="text">
      <span class="error-warning" id="first-name-error">This field is required</span>
</div>
```
This `aria` attribute should only be attached to form element if error is present. Otherwise attribute should not be mentioned.

Let me know if you want to discuss further about it

2024-04-12 13:59 UTC, AsifOni requested changes
Disclaimer content still going out of the grid and not matching Figma

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/84e8b9a6-5692-4d97-a917-8d9a2ed84544)

Figma 

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/28729aa0-b5cc-4784-8a38-bacd8f88ea10)

2024-04-12 14:16 UTC, AsifOni approved these changes

2024-04-12 14:17 UTC, merged