Worked on Signin page
alaminShaheen/irc-ui pull request #28
Opened 2024-04-22 22:30 UTC by farzanashampa7

2024-04-23 16:28 UTC, AsifOni requested changes
UI is not matching Figma

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/2ff5125e-7f78-45cb-9e04-26fcd99abdad)


1. Gap should be 48px as per Figma
2. Gap should be 24px as per Figma
3. Text color not matching

2024-04-23 16:31 UTC, AsifOni requested changes

2024-04-23 16:31 UTC, AsifOni commented on src/components/SigninForm/supplement/SigninForm.test.tsx
> +describe("SigninForm", () => {
Updates description. This is should be Signin Form

2024-04-23 16:31 UTC, AsifOni commented on src/components/SigninForm/supplement/SigninForm.test.tsx
> +  it("disables signup button until all fields and checkboxes are completed", () => {
Update description. It's not signup button

2024-04-23 16:31 UTC, AsifOni commented on src/components/SigninForm/supplement/SigninForm.test.tsx
> +  it("enables the signup button when all fields are valid and navigates to the base step form on form submit", async () => {
Update description

2024-04-25 15:01 UTC, alaminShaheen requested changes

2024-04-25 15:01 UTC, alaminShaheen commented on src/components/SigninForm/supplement/SigninForm.test.tsx
> +    () => {
@farzanashampa7 apu, i think, its better to use waitFor here instead of empty function. Any code within the empty function isn't actually executing.

2024-04-25 15:01 UTC, alaminShaheen commented on src/components/SigninForm/supplement/SigninForm.test.tsx
> +    await userEvent.click(loginButton);
This button click isn't supposed to work because the login button is disabled in the beginning.

2024-04-25 15:01 UTC, alaminShaheen commented on src/components/SigninForm/supplement/SigninForm.test.tsx
> +      expect(screen.getAllByText("This field is required")).toHaveLength(2);
@farzanashampa7 apu please use the translation key instead of using the english text because text can be in french as well.

2024-04-25 19:46 UTC, AsifOni commented on src/components/SigninForm/supplement/SigninForm.test.tsx
> +    () => {
We can delete this test case, since validation has been checked inside the individual element. We don't need to do redundant checking

2024-04-25 19:47 UTC, AsifOni approved these changes

2024-04-25 20:03 UTC, alaminShaheen approved these changes

2024-04-25 20:05 UTC, merged