Applicant information page
alaminShaheen/irc-ui pull request #31
Opened 2024-04-28 15:06 UTC by alaminShaheen

Added:
1. stepper context
2. translations
3. form functionality

2024-04-29 20:29 UTC, AsifOni requested changes
**UI Discrepencies**

1. Gap is missing

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/a4d6e1be-564b-428c-aa5c-ac67b10def52)

2. Underline missing

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/7c268eab-24e6-44f2-8f57-c594adf4e437)

3. Button typography not matching Figma

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/97a41e45-779d-4bc9-b6d3-718a0ea1ae71)

4. Wider space is missing

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/c7ab23d6-3dab-4728-966c-bd18df86d4ea)

5. Remove Back button - Confirmed with Business

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/0fe1d2d5-d511-491b-8639-aabbf26aa770)


6. Z-index needs to be fixed

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/7c60c16e-51ac-45fe-ad86-8398f4cbf7ef)

7. Content and Typography design not matching Figma

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/cdf16df6-a333-4dd4-956c-46cef12db791)

8. Error message color and box shadow is missing as per Figma

2024-04-29 20:29 UTC, AsifOni commented on src/components/Stepper/ApplicantInformationForm/ApplicantInformationForm.tsx
> +      </Trans>
We have these checkbox content used in Signup, Confirm Identity and then Application Agreement page. Can we make this a component?

2024-04-29 20:29 UTC, AsifOni commented on src/components/Stepper/ApplicantInformationForm/supplement/ApplicantInformationForm.test.tsx
We need test cases to cover error scenario for each field

2024-04-29 20:29 UTC, AsifOni commented on src/components/Stepper/StepperSidebar/StepperSidebar.tsx
> +            <Fragment key={step.id}>
Let's not rely on only `id`. Add some wording so that it can be completely unique

2024-05-02 23:46 UTC, alaminShaheen commented on src/components/Stepper/ApplicantInformationForm/supplement/ApplicantInformationForm.test.tsx
Bhai the errors for each and every field is already included in the unit tests

2024-05-05 17:32 UTC, AsifOni requested changes
@alaminShaheen 

**UI Issue**

At below viewport, UI looks squeezed. Left container should have more width compare to Sidebar stepper (right container).

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/c6a13269-41ad-40aa-a23c-670bfaec3b3b)

**Changes I made on your branch**

- Created `FormError` component and added test file
- Replaced all error message section from every component with `FormError`. 
- Added `aria-described` property to missing form elements. This was **missing** in new Form. Please keep this attribute in mind as it's absolutely important for Form to meet AODA

**Note**

Reasons for creating `FormError` component are

- It's used widely in all Form related components
- It's structure is different now since you added info icon. For future, if we need to adjust the UI again, then we will have only one place to change

For similar kind of situation, please think it thoroughly before working on development and create component model accordingly

2024-05-06 19:30 UTC, AsifOni approved these changes

2024-05-06 19:31 UTC, merged