Refactored password validation indicators in signup form
alaminShaheen/irc-ui pull request #32
Opened 2024-05-01 20:13 UTC by farzanashampa7

2024-05-01 20:54 UTC, AsifOni requested changes
It seems emoji is allowed. Please check the regEx, I think we need to block emojis to be set as password

![image](https://github.com/alaminShaheen/irc-ui/assets/124192994/c96a9630-7982-4e65-a6f4-b5b24d416220)

2024-05-01 20:54 UTC, AsifOni commented on src/components/FormElements/Password/supplement/Password.test.tsx
There is no test to validate if emoji is passed, then field should throw error. Please add the test case

2024-05-01 20:54 UTC, AsifOni commented on src/components/SignupForm/SignupForm.tsx
> +              />
In all component, same `passwordValidationRegEx` has been passed. Two approach can be taken here

1. Don't pass regEx as prop rather use `passwordValidationSchema` directly inside component OR
2. Pass only specific regEx

2024-05-01 21:23 UTC, farzanashampa7 commented on src/components/FormElements/Password/supplement/Password.test.tsx
<img width="1440" alt="Screenshot 2024-05-01 at 5 21 02 PM" src="https://github.com/alaminShaheen/irc-ui/assets/61857690/17b4d9a2-9a95-43a1-afeb-2c6dbbf2c073">

vaiya I tested at my end and here emoji isn't allowed, not sure if I am missing something

2024-05-01 21:29 UTC, farzanashampa7 commented on src/components/FormElements/Password/supplement/Password.test.tsx
Vaiya do we want to block typing emojis or to throw an error when emoji is passed?

2024-05-01 22:14 UTC, AsifOni commented on src/components/FormElements/Password/supplement/Password.test.tsx
We want to throw an error while emoji is typed

2024-05-02 15:55 UTC, AsifOni approved these changes

2024-05-02 15:55 UTC, merged